version: '3.8'

services:
  react-app:
    build:
      context: .
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
    container_name: react-app
    restart: always
    ports:
      - '127.0.0.1:8080:80'
