name: Deploy React App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to VPS via SSH
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.'
          target: '/home/root/app' # замените на путь на VPS

      - name: SSH & Rebuild Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: SENTRY_AUTH_TOKEN,VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY
          script: |
            cd /home/root/app
            echo "🛑 Останавливаем контейнеры..."
            docker-compose down
            echo "🧹 Очищаем неиспользуемые образы, контейнеры и тома..."
            docker system prune -af --volumes
            echo "🚀 Собираем и запускаем..."
            export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            export VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
            export VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
            docker-compose build
            docker-compose up -d
