name: Deploy React App to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd /home/react-app

            echo "📥 Pull latest code..."
            git pull origin main

            echo "🛑 Stop and clean containers..."
            docker compose down
            docker container prune -f
            docker image prune -f

            echo "🚀 Build and start..."
            docker compose up -d --build
          EOF
